cb-event-forwarder:                                                                          
      #image: cbsdk:latest                                                          
      build: .                                                                      
      dockerfile: Dockerfile                                                  
      ports:                                                                        
        - "5000:80"                                                                 
      volumes:                                                                      
        - ./:/vol/cb-event-forwarder      
